language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
#  - RAILS_ENV=test bundle exec teaspoon -q --coverage-reports=cobertura --format=tap --server-port 6374 --server-timeout 500
  - RAILS_ENV=test bundle exec rspec spec
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database projects_test;' -U postgres
services:
  - elasticsearch

addons:
  postgresql: '9.3'
