language: ruby
rvm:
  - 2.0.0
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec teaspoon -q --coverage-reports=cobertura --format=tap
  - RAILS_ENV=test bundle exec rspec spec
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
before_script:
  - mysql -e 'create database projects_test'
services:
  - elasticsearch
