$("script[src^='/assets/models']").attr "data-cover", "data-cover"
$("script[src^='/assets/collections']").attr "data-cover", "data-cover"
$("script[src^='/assets/utils']").attr "data-cover", "data-cover"
$("script[src^='/assets/views']").attr "data-cover", "data-cover"
$("script[src^='/assets/graphs']").attr "data-cover", "data-cover"
$("script[src^='/assets/manager']").attr "data-cover", "data-cover"
$("script[src^='/assets/routers']").attr "data-cover", "data-cover"
